#ifndef THREAD_EVENT_HANDLER_H
#define THREAD_EVENT_HANDLER_H

#include "esp_event.h"

#ifdef __cplusplus
extern "C" {
#endif


/**
 * @brief OpenThread event handler.
 *
 * This function handles events generated by the OpenThread stack.
 *
 * @param arg           Unused context argument.
 * @param event_base    Base identifier for the event.
 * @param event_id      Identifier for the specific event.
 * @param event_data    Pointer to event-specific data.
 */
void thread_event_handler(void *arg, const esp_event_base_t event_base, int32_t event_id, void *event_data);

#ifdef __cplusplus
}
#endif

#endif // THREAD_EVENT_HANDLER_H
